In [5]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import matplotlib.pyplot as plt 
import pandas as pd

In [5]:
root = "/home/endtheme/git/bird-class/data/"
txt_path = os.path.join(root, "train.txt")

a = pd.read_csv(txt_path, sep=" ", names= ["path", "label"])
a

path  label
0     Black_footed_Albatross_0004_2731401028.jpg      0
1     Black_footed_Albatross_0008_1384283201.jpg      0
2      Black_footed_Albatross_0011_820118444.jpg      0
3     Black_footed_Albatross_0003_2981373810.jpg      0
4     Black_footed_Albatross_0021_2443213385.jpg      0
...                                          ...    ...
4824     Common_Yellowthroat_0012_2573777857.jpg    199
4825     Common_Yellowthroat_0002_2679007659.jpg    199
4826     Common_Yellowthroat_0009_2099303008.jpg    199
4827     Common_Yellowthroat_0008_2691070273.jpg    199
4828     Common_Yellowthroat_0016_2805250778.jpg    199

[4829 rows x 2 columns]

In [10]:
root = "/home/endtheme/git/bird-class/data/"
txt_path = os.path.join(root, "train.txt")
labels = []
img_paths = []
with open(txt_path, 'r') as file:
    for line in file:
# Remove any trailing characters like newlines or spaces
        line = line.strip().split(" ")
        # print("img: ", line[0])
        # print("label: ", int(line[1])) 
        labels.append(int(line[1]))
        img_paths.append(line[0])
data = pd.DataFrame({"path":img_paths,"label":labels})
data

path  label
0     Black_footed_Albatross_0004_2731401028.jpg      0
1     Black_footed_Albatross_0008_1384283201.jpg      0
2      Black_footed_Albatross_0011_820118444.jpg      0
3     Black_footed_Albatross_0003_2981373810.jpg      0
4     Black_footed_Albatross_0021_2443213385.jpg      0
...                                          ...    ...
4824     Common_Yellowthroat_0012_2573777857.jpg    199
4825     Common_Yellowthroat_0002_2679007659.jpg    199
4826     Common_Yellowthroat_0009_2099303008.jpg    199
4827     Common_Yellowthroat_0008_2691070273.jpg    199
4828     Common_Yellowthroat_0016_2805250778.jpg    199

[4829 rows x 2 columns]

In [1]:
data.label.hist()

NameError: name 'data' is not defined

In [12]:
from utils.utils import get_dataloader
from torchvision import datasets, transforms
batch_size = 4
data_path = "/home/endtheme/git/bird-class/data/"
import torchvision.transforms as transform
from torchvision.transforms import v2
import torchvision
transformer = transform.Compose([
                           transform.Resize((256, 256)),
                           transform.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
                           transform.RandomRotation(5),
                           transform.RandomGrayscale(),
                           transform.RandomResizedCrop(224),
                           transform.RandomHorizontalFlip(),
                           
                           transform.RandomAffine(degrees=11, translate=(0.1,0.1), scale=(0.8,0.8)),
                           transform.ToTensor(),
                           transform.Normalize((0.4124234616756439, 0.3674212694168091, 0.2578217089176178), 
                                               (0.3268945515155792, 0.29282665252685547, 0.29053378105163574))
])
shuffle = True

train_loader,test_loader = get_dataloader(data_path = data_path, transform = transform, batch_size = batch_size, shuffle = shuffle)




img:  Black_footed_Albatross_0004_2731401028.jpg
label:  0
img:  Black_footed_Albatross_0008_1384283201.jpg
label:  0
img:  Black_footed_Albatross_0011_820118444.jpg
label:  0
img:  Black_footed_Albatross_0003_2981373810.jpg
label:  0
img:  Black_footed_Albatross_0021_2443213385.jpg
label:  0
img:  Black_footed_Albatross_0026_2445548469.jpg
label:  0
img:  Black_footed_Albatross_0034_2134386992.jpg
label:  0
img:  Black_footed_Albatross_0013_2445550421.jpg
label:  0
img:  Black_footed_Albatross_0025_2446371730.jpg
label:  0
img:  Black_footed_Albatross_0033_2472109427.jpg
label:  0
img:  Black_footed_Albatross_0024_2444047518.jpg
label:  0
img:  Black_footed_Albatross_0009_2408326989.jpg
label:  0
img:  Black_footed_Albatross_0015_2446377484.jpg
label:  0
img:  Black_footed_Albatross_0031_2445546631.jpg
label:  0
img:  Black_footed_Albatross_0035_1357619035.jpg
label:  0
img:  Black_footed_Albatross_0018_2443206789.jpg
label:  0
img:  Black_footed_Albatross_0002_2293084168.jpg
label:  

In [2]:
# import importlib
# importlib.reload(model)

In [3]:
from trainer import Trainer
from model.baseline import BirdClassifier
model = BirdClassifier()
trainer = Trainer(model,a)
trainer.train()

/home/endtheme/miniconda3/envs/bird/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/endtheme/miniconda3/envs/bird/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|          | 0/10 [00:00<?, ?it/s]

tensor([ 57, 146,  95, 141])


/home/endtheme/git/bird-class/trainer.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels)


tensor([169,  49, 195, 184])
tensor([ 22, 176, 125,  65])
tensor([ 31,  93, 155,   2])
tensor([ 75,  49, 151, 114])
tensor([136, 196, 155,  80])
tensor([126,  50,  68, 160])
tensor([122, 102,  50, 180])
tensor([ 82,  13,  92, 106])
tensor([ 55,  18, 163,  91])
tensor([195,  39,  75,  44])
tensor([149, 133, 154,   2])
tensor([  6,  99, 117, 152])
tensor([  3, 191, 159,  73])
tensor([52, 72,  8, 39])
tensor([ 56, 126,  16, 155])
tensor([ 89, 158, 105,  18])
tensor([ 37,  10, 177,  97])
tensor([113,  91, 183, 105])
tensor([116,   8,   1, 191])
tensor([179,  37,   0, 138])
tensor([162,  80, 102,  11])
tensor([ 46, 128,  34,  53])
tensor([105, 179, 175,  82])
tensor([ 98,  81, 123, 190])
tensor([ 62,  53,  64, 130])
tensor([ 25, 142, 133, 161])
tensor([118,  65, 109,  78])
tensor([ 74, 100, 172, 160])
tensor([144,  78, 101, 157])
tensor([ 41, 111, 193, 129])
tensor([131, 143,  55,  75])
tensor([  8, 160, 184,   6])
tensor([114,  83,  10, 122])
tensor([137, 133, 144, 121])
tensor([195,  53, 

 10%|█         | 1/10 [06:13<56:03, 373.69s/it]

tensor([194,  58, 177,  35])
tensor([174,  45,  93,   2])
tensor([119,  18, 134,  99])
tensor([ 51,  49,  89, 107])
tensor([182,   4, 177,  23])
tensor([ 27, 196,  36, 132])
tensor([  4,  31, 143,  62])
tensor([32, 91, 78, 81])
tensor([197, 188,   5,  51])
tensor([  8,  50, 191,  65])
tensor([114,  44, 123, 121])
tensor([120,  78,  18,  83])
tensor([103,  93, 161,  58])
tensor([ 68, 194, 109,  10])
tensor([ 49, 161, 101, 114])
tensor([ 48, 180,   9,  20])
tensor([124,   7,  17, 157])
tensor([ 44, 126, 162, 191])
tensor([118, 149,  14,  92])
tensor([ 42, 123, 147, 176])
tensor([117, 115,  74,  40])
tensor([181,  24, 178,  27])
tensor([130, 148,  43,  64])
tensor([171, 165, 165,  18])
tensor([ 19, 130, 193, 150])
tensor([ 97, 122, 198,  92])
tensor([112,  35, 196,  50])
tensor([ 68,  40, 158, 168])
tensor([ 99, 174, 184,  35])
tensor([11, 88, 49, 77])
tensor([182, 112,  72,  42])
tensor([ 48,  95,  34, 113])
tensor([ 95,  52,  27, 103])
tensor([101, 126,  90, 172])
tensor([119,  22,  78,

 20%|██        | 2/10 [12:06<48:10, 361.31s/it]

tensor([49])
Epoch [2/10], Loss: 4.663262303499197, Accuracy: 4.245185338579416%
tensor([94, 11, 62, 32])
tensor([37, 16, 32, 96])
tensor([187,  20,  15,  53])
tensor([ 12,  23,  42, 159])
tensor([ 1, 51, 82,  2])
tensor([129,  18,  86,  15])
tensor([104,  97,   2, 130])
tensor([183, 195, 153,  60])
tensor([ 46, 168,  58, 109])
tensor([155, 103, 148, 147])
tensor([161,  99, 180, 157])
tensor([194,  19,  44,  88])
tensor([ 61,  31,   7, 155])
tensor([ 88,  32, 114,  31])
tensor([118,  91, 176, 180])
tensor([ 91, 180,  64, 122])
tensor([170,  58, 107,   8])
tensor([155, 169,  73, 142])
tensor([ 72,   9, 177, 120])
tensor([185,  81, 115,   6])
tensor([115,  76, 108,  27])
tensor([109,  73, 171, 166])
tensor([147, 187, 132, 157])
tensor([143, 166, 190,  59])
tensor([117,   5, 145,   2])
tensor([ 71,  56, 153,  47])
tensor([145,  92, 126,  83])
tensor([141, 126, 196,  20])
tensor([ 35, 192,  20,   5])
tensor([127, 152,  85, 124])
tensor([  6, 176, 125,   3])
tensor([ 23, 114,  60, 130])
ten

 30%|███       | 3/10 [17:56<41:33, 356.17s/it]

Epoch [3/10], Loss: 4.060170761204713, Accuracy: 9.29799130254711%
tensor([ 58,  72,   6, 117])
tensor([130,  54, 173, 117])
tensor([197,  95, 173, 163])
tensor([ 18, 143, 122, 181])
tensor([ 67,  75,  38, 148])
tensor([194,  92,  17,  33])
tensor([ 74,  86, 127, 162])
tensor([117,  87, 193, 100])
tensor([ 25, 174, 137, 162])
tensor([182, 190, 199, 119])
tensor([ 19,  57, 181, 126])
tensor([126,  80, 140, 138])
tensor([ 97, 188, 180, 188])
tensor([161, 160, 176, 110])
tensor([ 35, 185,  58, 139])
tensor([ 82,  32,  32, 143])
tensor([ 31, 100, 151,  77])
tensor([ 11,  82,  32, 142])
tensor([139, 129, 152, 147])
tensor([195,  66,  42, 113])
tensor([152, 141, 162,  32])
tensor([ 11, 136, 146,   4])
tensor([114,  96, 198,  40])
tensor([140,  70,  73,  41])
tensor([ 36, 173, 135,  85])
tensor([14, 18, 32, 62])
tensor([ 46, 147,  75, 152])
tensor([186,  66,   4, 115])
tensor([156, 147,  69, 118])
tensor([51, 92, 18,  0])
tensor([101, 169, 189, 166])
tensor([152, 115, 115,  24])
tensor([ 59, 

 40%|████      | 4/10 [24:10<36:18, 363.09s/it]

tensor([126])
Epoch [4/10], Loss: 3.6648783124243187, Accuracy: 15.531165872851522%
tensor([ 89,  32, 142, 118])
tensor([126, 172, 110, 136])
tensor([128,  95,  13, 114])
tensor([114,  26,  36,  77])
tensor([ 27, 114,  59,  57])
tensor([  1, 152,  61, 178])
tensor([142, 130,  89, 159])
tensor([93, 54, 10, 51])
tensor([184,  42,  30, 124])
tensor([125,  47,  58, 175])
tensor([ 87, 193,   1,  98])
tensor([128,  73,  63,  17])
tensor([138,  49,  91,  94])
tensor([146, 169,  58,  19])
tensor([ 33, 116, 112, 193])
tensor([ 24, 171,  18,  71])
tensor([ 34,  42, 194, 111])
tensor([130, 106,  93, 191])
tensor([147, 185, 117,  46])
tensor([136, 127,  78,  81])
tensor([105, 148, 196, 144])
tensor([109,  82, 118,  26])
tensor([165,  92, 167, 142])
tensor([ 19, 104,  88, 162])
tensor([157,  89, 109, 132])
tensor([113, 164, 175,  36])
tensor([31, 14, 16,  7])
tensor([180, 117,  49,  82])
tensor([153,  73, 158, 184])
tensor([102,  89,  23, 144])
tensor([175,  55, 184,  53])
tensor([123,  15, 141, 19

 50%|█████     | 5/10 [30:50<31:22, 376.49s/it]

tensor([168, 194,  63,  99])
tensor([ 98,   6, 106,  84])
tensor([30, 30, 86, 64])
tensor([124, 123, 170,  77])
tensor([ 96, 126, 199,  59])
tensor([139, 141, 178, 155])
tensor([158,  49,  64,  57])
tensor([179, 169,   9,  54])
tensor([118, 157, 188,  46])
tensor([153,  18, 155,  68])
tensor([ 96, 125, 160, 193])
tensor([102, 161, 130,  82])
tensor([ 93, 134, 126,  32])
tensor([159,  30, 136,  76])
tensor([115, 146, 109, 109])
tensor([145,  48,  42,  30])
tensor([178,  47, 140, 125])
tensor([ 70, 176,   2, 142])
tensor([191, 137,  24, 191])
tensor([157, 176, 163, 139])
tensor([184,  66,  89,   7])
tensor([  4, 197, 169,  39])
tensor([ 79, 176,  88, 131])
tensor([162, 104,   4,  27])
tensor([195,   8,   9, 100])
tensor([197, 188,  51,  68])
tensor([119, 186, 188, 133])
tensor([ 47, 105, 125,  42])
tensor([76, 30,  1, 78])
tensor([  2, 168,  72,  38])
tensor([140,  62,  98,  68])
tensor([132, 198, 154,  76])
tensor([158,   4,  19,  94])
tensor([123, 135, 158,  50])
tensor([47, 46, 87, 42

 60%|██████    | 6/10 [36:26<24:10, 362.65s/it]

tensor([148])
Epoch [6/10], Loss: 3.0417389851433554, Accuracy: 25.71961068544212%
tensor([ 86, 148, 163,  55])
tensor([127, 116, 154, 150])
tensor([ 18,   0,  11, 105])
tensor([184, 188,  45,  25])
tensor([114,  29, 128,  95])
tensor([119,  57, 160, 118])
tensor([174,   3, 160, 169])
tensor([131, 164, 163,  34])
tensor([ 68, 183, 107,  42])
tensor([187, 165,  59,  39])
tensor([ 73, 132,  25, 155])
tensor([194,  74,   8, 128])
tensor([  2,  43, 182, 177])
tensor([ 37,  28, 149, 184])
tensor([ 56, 155, 177,  59])
tensor([ 97,  14,  13, 145])
tensor([ 18,  83,  84, 191])
tensor([ 49, 187,  30, 126])
tensor([ 93, 158, 179, 172])
tensor([185, 160, 184, 142])
tensor([ 39, 173, 148,  42])
tensor([109,  92,  55,  47])
tensor([154, 120,  34,  94])
tensor([102, 174, 192,   0])
tensor([ 44, 140, 159, 127])
tensor([109, 117,  90, 155])
tensor([ 56,  14, 135,  65])
tensor([ 22,  63,  20, 187])
tensor([172, 150, 123, 168])
tensor([ 14,  94,  40, 139])
tensor([ 89,  52, 176,  78])
tensor([184,  50, 

 70%|███████   | 7/10 [42:34<18:13, 364.55s/it]

Epoch [7/10], Loss: 2.839552057401234, Accuracy: 30.19258645682336%
tensor([ 52, 132,  76,  74])
tensor([ 52,  58, 121,  27])
tensor([96, 96, 19, 28])
tensor([173, 100,  79,  12])
tensor([112,  74,  64,  19])
tensor([ 91, 159, 143, 105])
tensor([ 87, 147, 102, 103])
tensor([112,  74, 190, 184])
tensor([56, 80, 73, 34])
tensor([161,  33,  19,  69])
tensor([34, 20, 10, 69])
tensor([156, 134,   7,   6])
tensor([ 33,   5,  12, 179])
tensor([ 79,   7,  22, 142])
tensor([156, 113, 177, 161])
tensor([134, 183, 124,   3])
tensor([176, 155,  42, 170])
tensor([124, 170, 159,  53])
tensor([ 68, 116,  89,  50])
tensor([ 78, 114, 165, 126])
tensor([107, 183, 133,  97])
tensor([182, 153, 180,  82])
tensor([197,  36, 136,  66])
tensor([ 89, 124, 184,  51])
tensor([125,  11,  68, 196])
tensor([130, 134,   4,  81])
tensor([ 29,  98,  40, 150])
tensor([134,  38, 183, 158])
tensor([132, 114,  86, 106])
tensor([  6, 109,  65,  58])
tensor([ 40, 178, 161, 143])
tensor([ 63, 163,  40, 151])
tensor([ 33,  11

 80%|████████  | 8/10 [49:47<12:52, 386.32s/it]

Epoch [8/10], Loss: 2.614709714637292, Accuracy: 34.810519776351214%
tensor([166, 152,  97,  45])
tensor([ 44, 130, 188, 125])
tensor([ 81, 136,  71, 173])
tensor([140,  93,   6, 191])
tensor([52, 73, 14, 13])
tensor([ 89, 174,  72,   0])
tensor([144, 197,  73, 113])
tensor([ 31, 133,  67,  78])
tensor([178, 123, 165,  38])
tensor([ 82, 128,  47,  72])
tensor([190,  42,  38, 130])
tensor([153, 190,  32, 139])
tensor([192,  74,  68, 164])
tensor([144,  96, 125, 168])
tensor([ 93,  51,  54, 174])
tensor([176,  68, 138, 155])
tensor([191, 115,  37,  25])
tensor([ 59,  80, 103, 114])
tensor([127, 199, 156, 188])
tensor([134, 180, 113, 128])
tensor([69, 14, 79,  5])
tensor([169, 118, 175, 115])
tensor([195,  72, 103, 174])
tensor([123, 189,  70, 143])
tensor([161,  39,  87,  91])
tensor([ 75, 192, 188, 137])
tensor([ 49,  88,  76, 116])
tensor([ 10, 142, 146, 175])
tensor([140, 133, 147,  14])
tensor([105, 159,  23, 182])
tensor([ 60,  36,  66, 137])
tensor([ 80, 161,  51,  59])
tensor([103

 90%|█████████ | 9/10 [55:08<06:05, 365.99s/it]

tensor([125,  24,  53, 176])
tensor([175])
Epoch [9/10], Loss: 2.4720299302890205, Accuracy: 37.50258852764548%
tensor([187, 125,  86, 165])
tensor([ 36,  74,  19, 183])
tensor([109, 178, 129,  74])
tensor([74, 35, 65, 45])
tensor([ 24,  45, 183, 102])
tensor([133, 195, 143,   3])
tensor([129,  94,  85,  57])
tensor([126,   6, 104,  13])
tensor([191,  65,  25,  14])
tensor([188, 146, 136,  45])
tensor([ 22,  24,  10, 178])
tensor([  2,  59, 180, 183])
tensor([  6,  72, 181, 187])
tensor([150, 190, 185, 154])
tensor([151,  90, 189, 167])
tensor([194,  92,  27, 122])
tensor([153,  69, 117, 120])
tensor([114, 168,  23, 114])
tensor([ 45, 182, 153,  47])
tensor([198, 175, 163,  94])
tensor([123,  27, 126,  15])
tensor([ 25,   3,  16, 155])
tensor([ 44, 141, 187,  63])
tensor([ 25, 163,  20, 127])
tensor([120, 169, 195,   5])
tensor([119, 125,  49,  48])
tensor([136, 118, 178, 162])
tensor([ 67,   0, 122, 136])
tensor([199, 150,  61, 187])
tensor([ 43, 107, 146, 114])
tensor([ 60,  63, 111,

100%|██████████| 10/10 [59:53<00:00, 359.30s/it]
